## INPUT

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = fr
    kb_variant = oss
    kb_model =
    kb_options = caps:swapescape
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
gestures:workspace_swipe_forever = true
