## KEYBINDINGS
# See https://wiki.hypr.land/Configuring/Keywords/
bind = $mainMod, q, killactive,
bind = $mainMod SHIFT, space, togglefloating,
bind = $mainMod, f, fullscreen,


# Move focus with mainMod + vim letters
bind = $mainMod, l, movefocus, r
bind = $mainMod, h, movefocus, l
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Move window with mainMod + SHIFT + vim letters
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla, workspace, 9
bind = $mainMod, agrave, workspace, 10

bind = $mainMod, ESCAPE, workspace, e+1
bind = $mainMod SHIFT, ESCAPE, workspace, e-1

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute, movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, minus, movetoworkspace, 6
bind = $mainMod SHIFT, egrave, movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
bind = $mainMod SHIFT, ccedilla, movetoworkspace, 9
bind = $mainMod SHIFT, agrave, movetoworkspace, 10

bind = $mainMod CTRL, ampersand, movecurrentworkspacetomonitor, l
bind = $mainMod CTRL, eacute, movecurrentworkspacetomonitor, r
bind = $mainMod CTRL, quotedbl, movecurrentworkspacetomonitor, u
bind = $mainMod CTRL, apostrophe, movecurrentworkspacetomonitor, d

bind = $mainMod, d, exec, ~/.config/scripts/set-current-gaps.sh 5 30
bind = $mainMod SHIFT, d, exec, ~/.config/scripts/set-current-gaps.sh 0 0

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod SHIFT, mouse:272, movewindow
bindm = $mainMod SHIFT, mouse:273, resizewindow

bind = $mainMod, r, togglegroup

bind = $mainMod, u, pin
