## AUTOSTART

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# exec-once = nm-applet &

exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
# exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = dunst &
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = kdeconnect-indicator &
exec-once = hyprpm reload -n
exec-once = hyprpaper
exec-once = /usr/bin/syncthing --no-browser

## ENVIRONMENT VARIABLES
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct

