## WINDOWS AND WORKSPACES

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# WORKSPACE 1 - Web browsers
windowrule {
    name = move-browser-to-workspace-1
    match:class = ^(firefox|firefox-esr|Firefox|Firefox-esr|chromium)$

    workspace = 1 # silent
}

# WORKSPACE 2 - Terminal
windowrule {
    name = move-alacritty-to-workspace-2
    match:class = ^(Alacritty)$

    workspace = 2 # silent
}

# WORKSPACE 3 - IDEs
windowrule {
    name = move-vscode-to-workspace-3
    match:class = ^(code)$

    workspace = 3 # silent
}

windowrule {
    name = move-jetbrains-to-workspace-3
    match:class = ^(jetbrains-phpstorm|jetbrains-idea)$

    workspace = 3 # silent
}

# WORKSPACE 4 - File browsers
windowrule {
    name = move-thunar-to-workspace-4
    match:class = ^(thunar)$

    workspace = 4 # silent
}

# WORKSPACE 5 - Dev utils
windowrule {
    name = move-datagrip-to-workspace-5
    match:class = ^(jetbrains-datagrip)$

    workspace = 5 # silent
}

windowrule {
    name = move-bruno-to-workspace-5
    match:class = ^(bruno)$

    workspace = 5 # silent
}

# WORKSPACE 6 - Games
windowrule {
    name = move-steam-to-workspace-6
    match:class = ^(steam)$

    workspace = 6 # silent
}

windowrule {
    name = move-mc-to-workspace-6
    match:class = ^(com-skcraft-launcher-Bootstrap|com-skcraft-launcher-FancyLauncher)$

    workspace = 6 # silent
}

windowrule {
    name = move-lutris-to-workspace-6
    match:class = ^(net.lutris.Lutris)$

    workspace = 6 # silent
}

# WORKSPACE 8 - Chatting
windowrule {
    name = move-vesktop-to-workspace-8
    match:class = ^(vesktop)$

    workspace = 8 # silent
}

windowrule {
    name = move-signal-to-workspace-8
    match:class = ^(signal)$

    workspace = 8 # silent
}

windowrule {
    name = move-mail-to-workspace-8
    match:class = ^(thunderbird)$

    workspace = 8 # silent
}

# WORKSPACE 9 - PWD Managers
windowrule {
    name = move-bw-to-workspace-9
    match:class = ^(Bitwarden)$

    workspace = 9 # silent
}

windowrule {
    name = move-kpxc-to-workspace-9
    match:class = ^(org.keepassxc.KeePassXC)$

    workspace = 9 # silent
}

# WORKSPACE 10 - Multimedia
windowrule {
    name = move-spotify-to-workspace-0
    match:class = ^(spotify)$

    workspace = 10 # silent
}

windowrule {
    name = move-jellyfin-to-workspace-0
    match:class = ^(com.github.iwalton3.jellyfin-media-player)$

    workspace = 10 # silent
}
