battery:
  i3:
    battery_name: BAT0
    format: "%status_text% %percentage%%"
    charging_text: 🔌
    discharging_text: 🔋
    prefix: "  "
  hyprland:
    battery_name: BAT0
    format: "%status_text% %percentage%%"
    charging_text: 🔌
    discharging_text: 🔋

temperature:
  i3_cpu:
    prefix: 🔥
    json_path: $.k10temp-pci-00c3.Tctl.temp1_input
    rounding: 0
    unit: "°C"
    suffix: " "
  hyprland_cpu:
    prefix: 🔥
    json_path: $.k10temp-pci-00c3.Tctl.temp1_input
    rounding: 0
    unit: "°C"

ip:
  tmux:
    interface: ['wlp1s0', 'enp4s0f4u2']
    no_ip: No address

backlight:
  i3:
    prefix: 
    device: amdgpu_bl0
  hyprland:
    prefix: 
    device: amdgpu_bl0
