battery:
  hyprland:
    battery_name: BAT0
    format: "%status_text% %percentage%%"
    charging_text: 🔌
    discharging_text: 🔋
    prefix: "  "

temperature:
  hyprland_cpu:
    json_path: $.k10temp-pci-00c3.Tctl.temp1_input
    rounding: 0
    unit: "°C"
    suffix: " "

ip:
  tmux:
    interface: ['wlan0', 'enp4s0f4u2']
    no_ip: No address
