#!/usr/bin/python3

import csv
import sys

if len(sys.argv) != 2 and len(sys.argv) != 3:
    print("Usage: casewhener <csv file> [separator]")
    exit(1)

with open(sys.argv[1]) as f:
    reader = csv.DictReader(f, fieldnames=['ours', 'theirs'], delimiter=';' if len(sys.argv) == 2 else sys.argv[2])

    for row in reader:
        print(f"WHEN '{row['ours'].strip()}' THEN '{row['theirs'].strip()}'")
