export ZSH=$HOME/.oh-my-zsh

# Setting the theme
ZSH_THEME="mattboll"

# Auto-title is messing tmux's tab name
DISABLE_AUTO_TITLE="true"

# Using git plugin & one to auto-expand aliases
plugins=(git globalias)
source $ZSH/oh-my-zsh.sh

# Err that should be automatic
alias "vim"="nvim"

# Some basic aliases
alias 'l'='ls -lah'
alias 'edi3'='vim ~/.config/i3/config && i3-msg restart'
alias 'cd..'='cd ..'
alias ':q'='exit'
alias 'svim'='sudo vim'

# Some docker related aliases
alias 'dka'='docker kill $(docker ps -q)'
alias 'd'='docker-compose exec php'
alias 'dc'='docker-compose'
alias 'dcd'='docker-compose -f docker-compose.dev.yml exec php'
alias 'dcp'='docker-compose -f docker-compose.prod.yml exec php'

# Some folder shortcuts
alias 'g'='cd ~/Git'

# Most importantly
export EDITOR=nvim

export PATH=$PATH:/home/oxodao/Android/Sdk/platform-tools

echo "Memo: "
cat ~/.memo
